	-- items
	["perfect_bear_fur"]			= {["name"] = "perfect_bear_fur",		["label"] = "Bear Fur",				["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_bear_fur"]			= {["name"] = "good_bear_fur",			["label"] = "Bear Fur",				["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_bear_fur"]			= {["name"] = "poor_bear_fur",			["label"] = "Bear Fur",				["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil, 	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_bighornram_hide"]		= {["name"] = "perfect_bighornram_hide",	["label"] = "Bighornram Hide",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_bighornram_hide"]		= {["name"] = "good_bighornram_hide",		["label"] = "Bighornram Hide",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_bighornram_hide"]		= {["name"] = "poor_bighornram_hide",		["label"] = "Bighornram Hide",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_boar_skin"]			= {["name"] = "perfect_boar_skin",		["label"] = "Boar Skin",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_boar_skin"]			= {["name"] = "good_boar_skin",			["label"] = "Boar Skin",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_boar_skin"]			= {["name"] = "poor_boar_skin",			["label"] = "Boar Skin",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_buck_fur"]			= {["name"] = "perfect_buck_fur",		["label"] = "Buck Fur",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_buck_fur"]			= {["name"] = "good_buck_fur",			["label"] = "Buck Fur",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_buck_fur"]			= {["name"] = "poor_buck_fur",			["label"] = "Buck Fur",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_bison_hide"]			= {["name"] = "perfect_bison_hide",		["label"] = "Bison Hide",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_bison_hide"]			= {["name"] = "good_bison_hide",		["label"] = "Bison Hide",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_bison_hide"]			= {["name"] = "poor_bison_hide",		["label"] = "Bison Hide",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_bull_hide"]			= {["name"] = "perfect_bull_hide",		["label"] = "Bull Hide",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_bull_hide"]			= {["name"] = "good_bull_hide",			["label"] = "Bull Hide",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_bull_hide"]			= {["name"] = "poor_bull_hide",			["label"] = "Bull Hide",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_deer_hide"]			= {["name"] = "perfect_deer_hide",		["label"] = "Deer Hide",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_deer_hide"]			= {["name"] = "good_deer_hide",			["label"] = "Deer Hide",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_deer_hide"]			= {["name"] = "poor_deer_hide",			["label"] = "Deer Hide",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_elk_fur"]			= {["name"] = "perfect_elk_fur",		["label"] = "Elk Fur",				["weight"] = 1000,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_elk_fur"]			= {["name"] = "good_elk_fur",			["label"] = "Elk Fur",				["weight"] = 1000,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_elk_fur"]			= {["name"] = "poor_elk_fur",			["label"] = "Elk Fur",				["weight"] = 1000,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_redfox_fur"]			= {["name"] = "perfect_redfox_fur",		["label"] = "Redfox Fur",			["weight"] = 100,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_redfox_fur"]			= {["name"] = "good_redfox_fur",		["label"] = "Redfox Fur",			["weight"] = 100,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_redfox_fur"]			= {["name"] = "poor_redfox_fur",		["label"] = "Redfox Fur",			["weight"] = 100,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_greywolf_fur"]		= {["name"] = "perfect_greywolf_fur",		["label"] = "Wolf Fur",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_greywolf_fur"]			= {["name"] = "good_greywolf_fur",		["label"] = "Wolf Fur",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_greywolf_fur"]			= {["name"] = "poor_greywolf_fur",		["label"] = "Wolf Fur",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_merinosheep_wool"]		= {["name"] = "perfect_merinosheep_wool",	["label"] = "Sheep Wool",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_merinosheep_wool"]		= {["name"] = "good_merinosheep_wool",		["label"] = "Sheep Wool",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_merinosheep_wool"]		= {["name"] = "poor_merinosheep_wool",		["label"] = "Sheep Wool",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_pronghorn_fur"]		= {["name"] = "perfect_pronghorn_fur",		["label"] = "Pronghorn Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_pronghorn_fur"]			= {["name"] = "good_pronghorn_fur",		["label"] = "Pronghorn Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_pronghorn_fur"]			= {["name"] = "poor_pronghorn_fur",		["label"] = "Pronghorn Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_berkshirepig_skin"]		= {["name"] = "perfect_berkshirepig_skin",	["label"] = "Pig Skin",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_berkshirepig_skin"]		= {["name"] = "good_berkshirepig_skin",		["label"] = "Pig Skin",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_berkshirepig_skin"]		= {["name"] = "poor_berkshirepig_skin",		["label"] = "Pig Skin",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_panther_fur"]			= {["name"] = "perfect_panther_fur",		["label"] = "Panther Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_panther_fur"]			= {["name"] = "good_panther_fur",		["label"] = "Panther Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_panther_fur"]			= {["name"] = "poor_panther_fur",		["label"] = "Panther Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_cougar_fur"]			= {["name"] = "perfect_cougar_fur",		["label"] = "Cougar Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_cougar_fur"]			= {["name"] = "good_cougar_fur",		["label"] = "Cougar Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_cougar_fur"]			= {["name"] = "poor_cougar_fur",		["label"] = "Cougar Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_crackercow_hide"]		= {["name"] = "perfect_crackercow_hide",	["label"] = "Cow Hide",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_crackercow_hide"]		= {["name"] = "good_crackercow_hide",		["label"] = "Cow Hide",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_crackercow_hide"]		= {["name"] = "poor_crackercow_hide",		["label"] = "Cow Hide",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_coyote_fur"]			= {["name"] = "perfect_coyote_fur",		["label"] = "Coyote Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_coyote_fur"]			= {["name"] = "good_coyote_fur",		["label"] = "Coyote Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_coyote_fur"]			= {["name"] = "poor_coyote_fur",		["label"] = "Coyote Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_alpinegoat_hair"]		= {["name"] = "perfect_alpinegoat_hair",	["label"] = "Goat Hair",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_alpinegoat_hair"]		= {["name"] = "good_alpinegoat_hair",		["label"] = "Goat Hair",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_alpinegoat_hair"]		= {["name"] = "poor_alpinegoat_hair",		["label"] = "Goat Hair",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_peccarypig_skin"]		= {["name"] = "perfect_peccarypig_skin",	["label"] = "Pig Skin",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_peccarypig_skin"]		= {["name"] = "good_peccarypig_skin",		["label"] = "Pig Skin",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_peccarypig_skin"]		= {["name"] = "poor_peccarypig_skin",		["label"] = "Pig Skin",				["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_moose_fur"]			= {["name"] = "perfect_moose_fur",		["label"] = "Moose Fur",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_moose_fur"]			= {["name"] = "good_moose_fur",			["label"] = "Moose Fur",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_moose_fur"]			= {["name"] = "poor_moose_fur",			["label"] = "Moose Fur",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_angusox_hide"]		= {["name"] = "perfect_angusox_hide",		["label"] = "Ox Hide",				["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_angusox_hide"]			= {["name"] = "good_angusox_hide",		["label"] = "Ox Hide",				["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_angusox_hide"]			= {["name"] = "poor_angusox_hide",		["label"] = "Ox Hide",				["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_alligator_skin"]		= {["name"] = "perfect_alligator_skin",		["label"] = "Alligator Skin",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_alligator_skin"]			= {["name"] = "good_alligator_skin",		["label"] = "Alligator Skin",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_alligator_skin"]			= {["name"] = "poor_alligator_skin",		["label"] = "Alligator Skin",			["weight"] = 1500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_beaver_fur"]			= {["name"] = "perfect_beaver_fur",		["label"] = "Beaver Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_beaver_fur"]			= {["name"] = "good_beaver_fur",		["label"] = "Beaver Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_beaver_fur"]			= {["name"] = "poor_beaver_fur",		["label"] = "Beaver Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},

	["perfect_blackbear_fur"]		= {["name"] = "perfect_blackbear_fur",		["label"] = "Black Bear Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Perfect (* * *)"},
	["good_blackbear_fur"]			= {["name"] = "good_blackbear_fur",		["label"] = "Black Bear Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Good (* *)"},
	["poor_blackbear_fur"]			= {["name"] = "poor_blackbear_fur",		["label"] = "Black Bear Fur",			["weight"] = 500,	["type"] = "item",	["image"] = "rsg_hide.png",		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "Poor (*)"},
